version: '3.7'
services:
  app:
    build: .
    container_name: docker
    ports:
      - 3333:3333
    volumes:
      - .:/app

    command: yarn ts-node-dev --poll --respawn --transpile-only src/serve.ts
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: e
      POSTGRES_PASSWORD: e
      POSTGRES_DB: e
    ports:
      - 5432:5432
