version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: e
      POSTGRES_PASSWORD: e
      POSTGRES_DB: e
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - 3333:3333
    container_name: aplicativo
    depends_on:
      - db
